### ISSUE TITLE
Consider using records for AST types

### ISSUE THREAD

**Issue by CharlesTaylor7** [JordanMartinez/purescript-language-purescript#1]
I'm having trouble following the meaning of each argument in various constructors of the `Type` data type.

For example, the `ForAll` constructor takes 6 arguments:
```purs
ForAll :: a -> TypeVarVisibility -> String -> Maybe (Type a) -> Type a -> Maybe SkolemScope -> Type a
```

But it would easier to follow if it took a record like:
```purs
ForAll ::
  { ann :: ...
  , visibility :: ...
  , name :: ...
  , kind :: ...
  , type :: ...
  , skolem :: ..
  } -> Type a
```

I ended up resorting to reading source code instead of pursuit docs in attempt to understand this:
https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Types.hs#L371-L379

**Comment by CharlesTaylor7** [comment]
@JordanMartinez Specifically when it comes to the 5th argument of type `Type a`, I don't understand what that represents. The rest of the structure makes decent sense.

**Comment by JordanMartinez** [comment]
Welcome to the frustrations of working with the compiler.

Using a record as an argument results in double boxing. In other words, the JS representation is
```js
{ tag: "Forall", value0: { ann, visibility, ...} }
```
rather than
```js
{ tag: "Forall", value0, value1, ...} }
//               ^ ann,  ^ visibility
```

> Specifically when it comes to the 5th argument of type Type a, I don't understand what that represents. The rest of the structure makes decent sense.

It's used to check for skolem escapes, and enables `RankN` types like [`ST`](https://pursuit.purescript.org/packages/purescript-st/6.2.0/docs/Control.Monad.ST.Internal#t:ST).
